# Generated by Django 2.0.5 on 2018-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='cleared',
            field=models.BooleanField(default=False, help_text='Is transaction cleared with the bank?'),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('CR', 'credit'), ('DR', 'debit')], help_text='Enter credit or debit', max_length=2),
        ),
    ]
